#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Tomas Pereira de Vasconcelos

# Short bio or description (displayed in the header)
# Mathematics PostGrad at King’s College London. Physics graduate from Royal Holloway, University of London. Interests in all things physics, maths and computer science.
description: Physics, math, tech

#Physics, Mathematics, Computing

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /assets/images/site_avatar_480.png


# kramdown supports mathjax
markdown: kramdown
mathjax: true


#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: tomasvasconcelos1@gmail.com
  facebook:
  flickr:
  github: https://github.com/TPVasconcelos
  telephone: +44(0)7874198319
  instagram: https://www.instagram.com/tomasvasconcelos/
  linkedin: https://www.linkedin.com/in/tomasvasconcelos/
  pinterest:
  rss:
  twitter: 
  stackoverflow: https://stackoverflow.com/users/6028742/tpvasconcelos
  youtube:
  googleplus:


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: tomasvasconcelos

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-111484808-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://tomasvasconcelos.com

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

include: ['_pages']

# workaroud the error:
# GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
github: [metadata]
