# Project information
site_name: Tomas Pereira de Vasconcelos
site_description: Tomas Pereira de Vasconcelos
site_author: Tomas Pereira de Vasconcelos <hello@tpvasconcelos.com>
site_url: https://tpvasconcelos.com

copyright: >
  Copyright &copy; 2020 - 2024 Tomas Pereira de Vasconcelos –
  <a href="#__consent">Change cookie settings</a>


# Navigation
nav:
  - Home: index.md
  - About:
      - about/index.md
      - about/professional-experience.md
      - about/education.md
      - about/research.md
  - OSS: open-source.md
  - Contacts: contacts.md


# Configuration
strict: true
site_dir: '../docs/'
extra_css:
  - stylesheets/extra.css
  - stylesheets/extra-font.css
  - stylesheets/extra-grid.css
  - stylesheets/extra-grid-extra.css
  - stylesheets/extra-admonition-buzz.css
theme:
  name: material
  custom_dir: overrides
  locale: en
  language: en
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.suggest
  palette:
    scheme: default
    # TODO: change to "teal"
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/logo.png
  logo: assets/images/logo.png


# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.superfences
  - meta
  - smarty
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


# Extra parameters
extra:
  generator: false
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:hello@tpvasconcelos.com
      name: "E-mail: hello@tpvasconcelos.com"
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/tpvasconcelos/
      name: "LinkedIn: tpvasconcelos"
    - icon: fontawesome/brands/github
      link: https://github.com/tpvasconcelos
      name: "GitHub: tpvasconcelos"
    - icon: fontawesome/brands/stack-overflow
      link: https://stackoverflow.com/users/6028742/tpvasconcelos
      name: "Stack Overflow: tpvasconcelos"
  analytics:
    provider: google
    property: G-XMP86N4E0H
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - manage
      - reject
      - accept
