# Project information
site_name: Tomas Pereira de Vasconcelos
site_description: An (aspiring) grandmaster of the Data Science Lifecycle.
site_author: Tomas Pereira de Vasconcelos <tomasvasconcelos1@gmail.com>
site_url: http://tomasvasconcelos.com


# Repository
repo_name: tpvasconcelos/tpvasconcelos.io
repo_url: https://github.com/tpvasconcelos/tpvasconcelos.io
edit_uri:


# Copyright
copyright: 'Copyright &copy; 2020 - 2021 Tomas Pereira de Vasconcelos'


# Navigation
nav:
    - Home: index.md
    - About:
      - Who am I?: about/index.md
      - about/professional-experience.md
      - about/education.md
      - about/research.md
    - contacts.md


# Configuration
strict: true
site_dir: '../docs/'
theme:
  name: material
  custom_dir: overrides
  language: en
  features:
    - navigation.sections
    - navigation.tabs
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/logo.png
  logo: assets/images/logo.png


# Extensions
markdown_extensions:
  - smarty
  - admonition
  - attr_list
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


# Google Analytics
google_analytics:
  - 'UA-111484808-1'
  - auto


# Parameters
extra:
  email: tomasvasconcelos1@gmail.com