# Project information
site_name: Tomas Pereira de Vasconcelos
site_description: An (aspiring) grandmaster of the Data Science Lifecycle.
site_author: Tomas Pereira de Vasconcelos <hello@tpvasconcelos.com>
site_url: https://tomasvasconcelos.com


# Repository
repo_name: tpvasconcelos.io
repo_url: https://github.com/tpvasconcelos/tpvasconcelos.io
edit_uri: ''


# Copyright
copyright: 'Copyright &copy; 2020 - 2022 Tomas Pereira de Vasconcelos'


# Navigation
nav:
    - Home: index.md
    - About:
      - about/index.md
      - about/professional-experience.md
      - about/education.md
      - about/research.md
    - Contacts: contacts.md


# Configuration
strict: true
site_dir: '../docs/'
theme:
  name: material
  custom_dir: overrides
  locale: en
  language: en
  features:
    - navigation.sections
    - navigation.instant
    - navigation.tabs
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/logo.png
  logo: assets/images/logo.png
  analytics:
    # Google Analytics
    gtag: G-278027779


# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - meta
  - smarty
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


# Parameters
extra:
  generator: false
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:hello@tpvasconcelos.com
      name: "E-mail: hello@tpvasconcelos.com"
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/tpvasconcelos/
      name: "LinkedIn: tpvasconcelos"
    - icon: fontawesome/brands/github
      link: https://github.com/tpvasconcelos
      name: "GitHub: tpvasconcelos"
    - icon: fontawesome/brands/stack-overflow
      link: https://stackoverflow.com/users/6028742/tpvasconcelos
      name: "Stack Overflow: tpvasconcelos"
